[package]
name = "elys-bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.1.4", features = ["staking"] }
cw-storage-plus = "0.15.1"
cosmwasm-schema = "1.1.4"
